### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'find' - team_batting, team_pitching

### ISSUE THREAD

**Issue by windowshopr** [jldbc/pybaseball#153]
Trying to run this code:

```
from pybaseball import team_game_logs, team_batting, team_pitching, team_results, team_batting_bref

pulled_team_game_log = team_game_logs(2019, "NYY", "batting")
pulled_team_game_log.to_csv('./NYY_team_game_log.csv', index=False)

pulled_team_game_log = team_batting("NYY", 2019)
pulled_team_game_log.to_csv('./NYY_team_batting.csv', index=False)

pulled_team_game_log = team_pitching("NYY", 2019)
pulled_team_game_log.to_csv('./NYY_team_pitching.csv', index=False)

pulled_team_game_log = team_results(season=2019, team="NYY")
pulled_team_game_log.to_csv('./NYY_team_results.csv', index=False)

data = team_batting_bref('NYY', 2019)
data.to_csv('./bref_team_batting.csv', index=False)
```

`team_batting` and `team_pitching` returns:

```
Traceback (most recent call last):
  File "baseball_scraper.py", line 6, in <module>
    pulled_team_game_log = team_batting("NYY", 2019)
  File "C:\Users\chalu\AppData\Local\Programs\Python\Python37\lib\site-packages\pybaseball\team_batting.py", line 74, in team_batting
    table = get_table(soup, ind)
  File "C:\Users\chalu\AppData\Local\Programs\Python\Python37\lib\site-packages\pybaseball\team_batting.py", line 23, in get_table
    table_body = table.find('tbody')
AttributeError: 'NoneType' object has no attribute 'find'
```

and `team_results` returns:

```
C:\Users\chalu\Documents\Python_Scripts\Baseball>python baseball_scraper.py
Traceback (most recent call last):
  File "baseball_scraper.py", line 12, in <module>
    pulled_team_game_log = team_results(season=2019, team="NYY")
TypeError: 'module' object is not callable
```

Can you confirm if I'm using these functions correctly? Or if there's a fix needed. Thanks!! Love the program.

**Comment by windowshopr** [comment]
@schorrm  pybaseball==2.0.0, Python 3.7, Windows 10. Thinking maybe some elements have changed on the web pages?

**Comment by TheCleric** [comment]
@schorrm this looks like it predates any of our current changes.

@windowshopr I think the issue is because the Fangraphs team_batting and team_pitching work differently than the bref.

Here's what team_batting expects (and team_pitching is virtually identical):

`def team_batting(start_season, end_season=None, league='all', ind=1):`

So in your case you would need to call `team_batting(2019)` and then filter the Dataframe down to just NYY.

As far as the team_results, that's a module within the package. You are probably looking for `schedule_and_record`.

**Comment by windowshopr** [comment]
Worked like a charm. New code that works looks like this. Thanks! Closing.

```
from pybaseball import team_game_logs, team_batting, team_pitching, team_results, team_batting_bref
from pybaseball.team_results import schedule_and_record

pulled_team_game_log = team_game_logs(2019, "NYY", "batting")
pulled_team_game_log.to_csv('./NYY_team_game_log.csv', index=False)

pulled_team_game_log = team_batting(2019)
pulled_team_game_log.to_csv('./NYY_team_batting.csv', index=False)

pulled_team_game_log = team_pitching(2019)
pulled_team_game_log.to_csv('./NYY_team_pitching.csv', index=False)

pulled_team_game_log = schedule_and_record(2019, "NYY")
pulled_team_game_log.to_csv('./NYY_team_results.csv', index=False)

data = team_batting_bref('NYY', 2019)
data.to_csv('./bref_team_batting.csv', index=False)
```
