### ISSUE TITLE
team_batting issue

### ISSUE THREAD

**Issue by artchaidez** [jldbc/pybaseball#75]
from pybaseball import team_batting
team_batting(2016)

My error returns this:

team_batting(2016)
Traceback (most recent call last):

  File "<ipython-input-11-4a0c3d5fd9ca>", line 1, in <module>
    team_batting(2016)

  File "/opt/anaconda3/lib/python3.7/site-packages/pybaseball/team_batting.py", line 76, in team_batting
    table = get_table(soup, ind)

  File "/opt/anaconda3/lib/python3.7/site-packages/pybaseball/team_batting.py", line 26, in get_table
    rows = table_body.find_all('tr')

AttributeError: 'NoneType' object has no attribute 'find_all'

**Comment by schorrm** [comment]
Fixed in #82
